import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";
import WhatsAppFloat from "@/components/WhatsAppFloat";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <WhatsAppFloat />
        <Toaster />
        <footer className="w-full border-t bg-zinc-50 py-8 text-center dark:bg-black">
          <div className="mx-auto max-w-4xl text-sm text-zinc-600 dark:text-zinc-400">
            © {new Date().getFullYear()} Catálogo — Todos os direitos reservados
          </div>
        </footer>
      </body>
    </html>
  );
}
